# Working with numpy

In [1]:
import numpy as np

In [2]:
a = [4,5,3]
b = [7,5,2]
print(a+b)

[4, 5, 3, 7, 5, 2]


In [3]:
a = np.array([1,2,8])
b = np.array([7,2,6])
print(a+b)

[ 8  4 14]


In [4]:
m = np.array([[4,2,6],[2,1,8],[6,9,4]])
m

array([[4, 2, 6],
       [2, 1, 8],
       [6, 9, 4]])

In [6]:
a.ndim

1

In [7]:
a.shape

(3,)

In [8]:
m.ndim

2

In [9]:
m.shape

(3, 3)

In [10]:
print(m.min())
print(m.max())
print(m.mean())
print(m.std())

1
9
4.666666666666667
2.6246692913372702


### Mathematical computation with numpy

In [11]:
m

array([[4, 2, 6],
       [2, 1, 8],
       [6, 9, 4]])

In [13]:
print(np.mean(m),
np.median(m),
np.std(m),
np.var(m))

4.666666666666667 4.0 2.6246692913372702 6.888888888888889


In [14]:
print(np.sin(np.deg2rad(90)))

1.0


In [15]:
print(np.log10(1000))
print(np.exp(1.25))

3.0
3.4903429574618414


## Generating arrays with numpy

In [17]:
x = np.arange(start=3,stop=25,step=1.5)
x

array([ 3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. , 16.5, 18. ,
       19.5, 21. , 22.5, 24. ])

In [20]:
x = np.linspace(start=3,stop=25,num=6)
x

array([ 3. ,  7.4, 11.8, 16.2, 20.6, 25. ])

In [21]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [22]:
x = np.ones((2,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Generate random numbers with numpy

In [23]:
# generating an array with uniform distribution between 0 to 1
x = np.random.rand(10)
x

array([0.7512821 , 0.10410138, 0.30170082, 0.66000431, 0.67328522,
       0.72181342, 0.59807094, 0.0340924 , 0.32760084, 0.48239739])

In [24]:
# generating normal distribution, with mean = 0, std = 1
x = np.random.randn(10)
x

array([ 1.02428874,  0.76097992, -0.97183937, -1.19770672, -1.02289779,
       -1.9642653 ,  0.12259568, -0.27082308, -0.97356985,  1.55440257])

In [30]:
x = np.random.randn(200)
print(x.mean(),x.std())

0.04236986331078365 1.04960887830001


In [25]:
# generate integer random numbers
x = np.random.randint(10,200,5)
x

array([ 18, 123,  55,  54,  67])

In [26]:
# generate integer random numbers
x = np.random.randint(10,200,5)
x

array([ 94, 148,  41, 195, 152])

In [27]:
# generate integer random numbers
x = np.random.randint(10,200,5)
x

array([152,  76, 187,  19, 169])

In [28]:
np.random.seed(3)
# generate integer random numbers
x = np.random.randint(10,200,5)
x

array([116, 162, 141, 194,  10])

In [29]:
np.random.seed(3)
# generate integer random numbers
x = np.random.randint(10,200,5)
x

array([116, 162, 141, 194,  10])

### Linear Algebra with numpy

In [31]:
m 

array([[4, 2, 6],
       [2, 1, 8],
       [6, 9, 4]])

In [32]:
np.linalg.inv(m)

array([[ 0.56666667, -0.38333333, -0.08333333],
       [-0.33333333,  0.16666667,  0.16666667],
       [-0.1       ,  0.2       ,  0.        ]])

In [33]:
np.linalg.matrix_rank(m)

3

In [34]:
np.linalg.det(m)

-119.99999999999997

    3x - 4y = 1
    4x + 2y = 16

In [35]:
# create a list of coefficients
a = [[3,-4],[4,2]]
# list of constants
b = [1,16]

np.linalg.solve(a,b)

array([3., 2.])