In [4]:
import numpy as np

## Numpy
    - numpy nd array
    - numpy matrix

In [2]:
x = [4,2,3]
y = [7,5,1]
print(x+y)

[4, 2, 3, 7, 5, 1]


In [5]:
x = np.array([4,2,3])
y = np.array([7,5,1])
print(x+y)

[11  7  4]


In [6]:
x = np.array([[7,5,2],[6,2,1],[9,6,3]])
x

array([[7, 5, 2],
       [6, 2, 1],
       [9, 6, 3]])

In [8]:
print(x.shape)
print(x.ndim)
print(x.size)

(3, 3)
2
9


In [10]:
print("the first columns ",x[:,0])
print("the last row ",x[2,:])

the first columns  [7 6 9]
the last row  [9 6 3]


## Generating arrays and random numbers with numpy

In [ ]:
x = np.arange(4,23,2)
x

In [ ]:
x = np.linspace(2,25,11)
x

In [ ]:
x = np.ones((2,3))
x

In [ ]:
x = np.zeros((2,4))
x

In [23]:
x = np.random.rand(2,5) # uniformly distributed random values - all values will b/w 0 to 1
x

array([[0.55226079, 0.57771037, 0.43203867, 0.66486418, 0.2791172 ],
       [0.67980771, 0.1853366 , 0.55417895, 0.63710518, 0.30523795]])

In [35]:
x = np.random.randn(2,5) # normally distributed random values with mean = 0, std = 1
x

array([[-0.91693642,  0.17985591, -0.65325903,  0.91431579, -1.18807377],
       [-0.06441186,  0.09540747,  0.38667427,  0.07895139, -0.35597805]])

In [28]:
x = np.random.randint(4,30,5)
x

array([24, 26,  7, 10, 21])

In [30]:
np.random.seed(6)
x = np.random.randint(4,30,5)
x

array([14, 13,  7, 24, 14])

In [31]:
np.random.seed(6)
x = np.random.randint(4,30,5)
x

array([14, 13,  7, 24, 14])

## linear algebra with numpy

In [36]:
x = np.array([[7,5,2],[6,2,1],[9,6,3]])
x

array([[7, 5, 2],
       [6, 2, 1],
       [9, 6, 3]])

In [37]:
np.linalg.inv(x)

array([[ 0.        ,  0.33333333, -0.11111111],
       [ 1.        , -0.33333333, -0.55555556],
       [-2.        , -0.33333333,  1.77777778]])

In [38]:
np.linalg.det(x)

-9.000000000000002

In [40]:
np.linalg.matrix_rank(x)

3

    4x + 7y = 26
    5x - 2y = 11

In [42]:
a = [[4,7],[5,-2]]
b = [26,11]
np.linalg.solve(a,b)

array([3., 2.])