# Linear Regression with numpy

<img src = "linear_regression.png">

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
area = [1.2,2.4,3.6,2.5,1.8,3.6,4.8,5.6,9.2,8.3,8.4,7.6,6.7,5.4,4.9]
price= [150,210,310,290,320,395,510,630,870,820,790,710,620,590,540]

In [14]:
len(area),len(price)

(15, 15)

In [15]:
x = np.array(area)
y = np.array(price)

In [24]:
LR = 0.002
m = 10
c = 15


for i in range(1000):
    # get predictions
    yhat = m*x + c
    
    # get error
    e = np.mean(np.square(y-yhat))
    
    # apply gradient descent
    dedm = 2*(yhat-y).dot(x)
    dedc = 2*(yhat-y).dot(np.ones(len(x)))
    
    m = m - LR*dedm
    c = c - LR*dedc
    
    print(e)
    
    #plt.scatter(x,y,c='g')
    #plt.plot(x,yhat,c='r')
    #plt.show()

242566.8
222086.15581027514
203351.46525008845
186213.8527402671
170537.13794252084
156196.75316585583
143078.75309213763
131078.90894819735
120101.87992321713
110060.45524422573
100874.86088426459
92472.12539160873
84785.4997984368
77753.92699727046
71321.55636677185
65437.299788215205
60054.42552300277
55130.18672258728
50625.48161748988
46504.54268394711
42734.6523170927
39285.88275030419
36130.85815309941
33244.53701628631
30604.013094351787
28188.3333226038
25978.331261529096
23956.474744268915
22106.726516029572
20414.416757528314
18866.126479053735
17449.580858138834
16153.55167289737
14967.768055382414
13882.834855471
12890.157966280347
11981.876017465967
11150.797893375282
10390.345579337712
9694.501881730523
9057.76260620547
8475.092813903502
7941.886807904262
7453.931531812163
7007.37308950684
6598.686119898833
6224.645783228265
5882.302136205679
5568.9566922853555
5282.140980732845
5019.596934038681
4779.258947765252
4559.237470209565
4357.803991426303
4173.377312280418
400

2107.8030300482696
2107.8030102903645
2107.802990975214
2107.8029720928976
2107.802953633712
2107.802935588179
2107.8029179470295
2107.8029007011983
2107.8028838418295
2107.8028673602626
2107.8028512480296
2107.8028354968556
2107.80282009865
2107.8028050455036
2107.8027903296793
2107.802775943624
2107.8027618799447
2107.8027481314184
2107.802734690985
2107.8027215517345
2107.8027087069217
2107.80269614995
2107.8026838743663
2107.802671873865
2107.8026601422853
2107.8026486735957
2107.8026374619094
2107.802626501463
2107.802615786631
2107.8026053119083
2107.8025950719116
2107.8025850613844
2107.802575275181
2107.802565708278
2107.802556355759
2107.802547212822
2107.802538274766
2107.8025295370044
2107.802520995047
2107.802512644507
2107.8025044810925
2107.802496500611
2107.802488698967
2107.8024810721467
2107.8024736162392
2107.8024663274086
2107.802459201913
2107.802452236094
2107.802445426371
2107.8024387692476
2107.8024322613014
2107.802425899195
2107.802419679654
2107.8024135994883


In [25]:
print(m,c)

87.47649851235937 73.78563913312819


## Linear Regression with sklearn

In [26]:
x = np.array(area).reshape(15,1)
y = np.array(price)

In [27]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [28]:
# train the model
model.fit(x,y)

LinearRegression()

In [29]:
model.coef_,model.intercept_

(array([87.47641167]), 73.7861808680504)

In [30]:
model.predict([[2.5]])

array([292.47721004])

## ########################.

In [33]:
from sklearn.linear_model import SGDRegressor
model = SGDRegressor(learning_rate='adaptive',max_iter=5000,tol=0.000001,random_state=5)
model.fit(x,y)

C:\Users\anshu\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_stochastic_gradient.py:1223: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


SGDRegressor(learning_rate='adaptive', max_iter=5000, random_state=5, tol=1e-06)

In [34]:
model.coef_,model.intercept_

(array([88.39175674]), array([68.04550169]))