In [1]:
import numpy as np

## Working with numpy
    - numpy nd arrays
    - numpy matrix

In [4]:
x = [3,2,6]
y = [4,1,7]
print(x+y)

[3, 2, 6, 4, 1, 7]


In [5]:
x = np.array([3,5,6])
y = np.array([7,4,2])
print(x+y)

[10  9  8]


In [6]:
x = np.array([[7,4,6],[3,9,8],[2,5,1]])
x

array([[7, 4, 6],
       [3, 9, 8],
       [2, 5, 1]])

In [7]:
print(x.shape)
print(x.ndim)
print(x.size)

(3, 3)
2
9


In [8]:
print("first columns ",x[:,0])
print("last row ",x[2,:])

first columns  [7 3 2]
last row  [2 5 1]


### Generating arrays & random numbers with numpy

In [9]:
x = np.arange(5,26,2)
x

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [10]:
x = np.linspace(2,25,11)
x

array([ 2. ,  4.3,  6.6,  8.9, 11.2, 13.5, 15.8, 18.1, 20.4, 22.7, 25. ])

In [13]:
x = np.ones((2,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
x = np.zeros((2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
x = np.random.rand(2,4) # unformly distrbuted random numbers between 0 to 1
x

array([[0.01717869, 0.80401055, 0.00342742, 0.78634602],
       [0.9813168 , 0.97224686, 0.44525307, 0.23648614]])

In [17]:
x = np.random.randn(2,3) # normally distributed random numbers with mean =0 and std = 1
x

array([[ 0.11593923,  1.56560317,  0.89630687],
       [-2.38920431, -0.82152546,  0.27288998]])

In [32]:
x = np.random.randint(4,60,5)
x

array([41, 53,  8, 41, 20])

In [41]:
np.random.seed(6)
x = np.random.randint(4,60,5)
x

array([14, 13, 39, 24, 46])

In [43]:
np.random.seed(6)
x = np.random.randint(4,6,10)
x

array([4, 5, 5, 4, 4, 5, 5, 4, 4, 4])

In [25]:
np.random.seed(6)
x = np.random.randint(4,60,5)
x

array([14, 13, 39, 24, 46])

### linear Algebra with numpy

In [44]:
x = np.array([[7,4,6],[3,9,8],[2,5,1]])
x

array([[7, 4, 6],
       [3, 9, 8],
       [2, 5, 1]])

In [45]:
np.linalg.inv(x)

array([[ 0.16939891, -0.1420765 ,  0.12021858],
       [-0.07103825,  0.0273224 ,  0.20765027],
       [ 0.01639344,  0.14754098, -0.27868852]])

In [46]:
np.linalg.det(x)

-183.00000000000009

In [47]:
np.linalg.matrix_rank(x)

3

    3x - 6y = 3
    4x + y  = 22

In [48]:
a = [[3,-6],[4,1]]
b = [3,22]
np.linalg.solve(a,b)

array([5., 2.])